# SOURCE_DIR tests


BIN_x1.SOURCE_DIR = src1
BIN_x1.SRC = main.cc file.cc

BIN_x2.SOURCE_DIR = src2
BIN_x2.SRC = main.cpp file.cpp

SOURCE_DIR = src1
BIN_x3.SRC  = *
BIN_x3.SRC2 = src2/file.cpp


include ../../Makefile.mk

## END
